### ISSUE TITLE
Shoes 3.3.0 beta

### ISSUE THREAD

**Issue by ccoupe** [Shoes3/shoes3#181]
There are betas of Shoes 3.3.0 at http://walkabout.mvmanila.com/public/shoes which I'll test in the next few day or two before announcing on the blog and mailing list. There's still some unfinished work for svg but it's good enough to let other folks poke at it.

**Comment by passenger94** [comment]
beware manual looks not up to date with svg ?
style= is implemented, aspect is true/false, no app section :-)

**Comment by BackOrder** [comment]
Gave a try to good-svgview.rb and it's very satisfying. Amazing work guys!

Shoes console did report the following:
```
Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'

Error in <unknown> line 0 | 2016-01-05 05:19:57 -0500
no implicit conversion of nil into String
good-svgview.rb:88:in `+'
good-svgview.rb:88:in `block (4 levels) in <main>'
good-svgview.rb:21:in `call'
good-svgview.rb:21:in `items='
good-svgview.rb:21:in `show_svg'
good-svgview.rb:55:in `block (4 levels) in <main>'
-e:1:in `call'
```

**Comment by passenger94** [comment]
hu ! When using the load button right ?

**Comment by passenger94** [comment]
change `@subid.text = '#'+ lb.text` to 
`@subid.text = '#'+ (lb.text.nil? ? "" : lb.text)`

**Comment by passenger94** [comment]
Makes me wonder, as we are dealing with a GtkComboBoxText shouldn't we provide a "default" or a fallback to an empty string ? or is it the user responsibility to check beforehand like here ?
Could happen here ; https://github.com/Shoes3/shoes3/blob/master/shoes/native/gtk.c#L1525 returns "" instead of Qnil (same on cocoa)

**Comment by ccoupe** [comment]
Nil is the correct answer for list_box.text when there is no selection. According to manual. If the sample was written to handle that, returning an empty string would break old code.

The manual still has rough spots (links, bold, italics...) I just wanted to get the basics in there and there is a lifetime of work needed in there. 

there is no style= defined in ruby.c for Svg

**Comment by ccoupe** [comment]
There is a very interesting section of the manual. Hello! -> Rules that mentions dangers for specifying a slot height. Perhaps the OSX bug is nearby?

**Comment by ccoupe** [comment]
New betas at http://walkabout.mvmanila.com/public/shoes 

FYI, I turned 65 years of age which in the USA is beginning of government benefits they can't afford. Official Old Fart.

**Comment by passenger94** [comment]
Thanks for sharing  !!!  Please, take all the benefits from that wisdom you've been granted :-)
Congratulations !!!  :+1:
