### ISSUE TITLE
Can not require Twitter Gem with Shoes

### ISSUE THREAD

**Issue by ardian** [Shoes3/shoes3#267]
Hello, I am having an issue when I open my shoes application, the moment I require the 'twitter' gem it doesn't run any of my code.

I am using shoes3 downloaded from the website.

```
Warn in <unknown> line 0 | 2016-08-18 16:29:27 +0200
WARNING: Nokogiri was built against LibXML version 2.9.2, but has dynamically loaded 2.9.3

Error in <unknown> line 0 | 2016-08-18 16:29:27 +0200
cannot load such file -- twitter
/home/ardian/.shoes/walkabout/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/home/ardian/.shoes/walkabout/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
twitter-shoes.rb:2:in `<main>'
/home/ardian/.shoes/walkabout/lib/shoes.rb:500:in `eval'
/home/ardian/.shoes/walkabout/lib/shoes.rb:500:in `visit'
/home/ardian/.shoes/walkabout/lib/shoes.rb:171:in `show_selector'
/home/ardian/.shoes/walkabout/lib/shoes.rb:199:in `block (4 levels) in splash'
-e:1:in `call'

```

**Comment by ccoupe** [comment]
How did you install the 'twitter' gem? It has to be installed by Shoes (and the ruby inside shoes). See the [wiki article ](https://github.com/Shoes3/shoes3/wiki/Gems). You can also use  the command line to install gems 
```
/home/ardian/.shoes/walkabout/shoes -g list -l 
/home/ardian/.shoes/walkabout/shoes -g install twitter
````

**Comment by ardian** [comment]
Thanks a lot, this fixed my issue.
