### ISSUE TITLE
Shoes Manual "Check" header

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#309]
1. Open manual
2. Go to search
3. Type "Check"
4. Click on the big CHECK header.
5. Open debug and you will see this error.

```Ruby
Error in <unknown> line 0 | 2017-02-02 10:32:21 +0200
bad arguments
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:48:in `eval'
(eval):1:in `block in dewikify_p'
(eval):1:in `call'
(eval):1:in `stack'
(eval):1:in `dewikify_p'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:48:in `eval'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:48:in `dewikify_p'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:115:in `block (2 levels) in dewikify'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:81:in `wiki_tokens'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:113:in `block in dewikify'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:380:in `instance_eval'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:380:in `block in open_methods'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:378:in `call'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:378:in `clear'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:378:in `open_methods'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:283:in `block (7 levels) in show_search'
-e:1:in `call'
```

**Comment by BackOrder** [comment]
**Shoes eBook** is underway and will be solving a whole lot of problems.

@ccoupe wouldn't it be a good thing to update current Shoes Manual with Picky for 3.3.3?!

**Comment by ccoupe** [comment]
Shoes Bbook is on hiatus and it won't solve this anytime soon.  If picky can deal with the odd shoes markup currently being used then yes, it should be part of 3.3.3

**Comment by BackOrder** [comment]
Yes, it can. The prototype was meant for an eventual replacement of ftsearch. No worries!

**Comment by BackOrder** [comment]
Search for `slider` and click on **Slider Sub-section under Elements** resulting in the same error as above.

**Comment by ccoupe** [comment]
Executive choice. I'm going to move this to 3.3.4 along with some other picky issues.
