### ISSUE TITLE
SVG segfault on non-existing file source

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#318]
Passing a non-existing file to svg cause Shoes to segfault. It should instead raise an exception that can be handled in Shoes and displayed in Shoes Console.

```ruby
Shoes.app do
   svg "crash.me", width: 100, height: 100
end
```
```
Failed SVG: Error opening file: No such file or directory
a.rb:3: [BUG] Segmentation fault
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0018 e:000017 CFUNC  :svg
c:0005 p:0013 s:0013 e:000012 BLOCK  a.rb:3 [FINISH]
c:0004 p:---- s:0011 e:000010 CFUNC  :instance_eval
c:0003 p:0010 s:0008 e:000007 LAMBDA eval:1 [FINISH]
c:0002 p:---- s:0004 e:000003 CFUNC  :call
c:0001 p:0000 s:0002 E:0020fc TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
-e:0:in `call'
eval:1:in `block in <main>'
eval:1:in `instance_eval'
a.rb:3:in `block in <main>'
a.rb:3:in `svg'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0xc) [0x7768E5FC]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObject+0x12) [0x7442AD52]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_print_backtrace+0x4b) [0x640AF005]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_vm_bugreport+0x78) [0x640AF082]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_bug_context+0x72) [0x63F7AAD6]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_get_next_signal+0xdb) [0x640356B9]
C:\Program Files (x86)\Shoes\cshoes.exe(WinMain+0x4f6) [0x00401A56]
C:\WINDOWS\System32\KERNELBASE.dll(UnhandledExceptionFilter+0x172) [0x744BD412]
C:\WINDOWS\SYSTEM32\ntdll.dll(LdrSetAppCompatDllRedirectionCallback+0x1ae9d) [0x776BE0BD]

-- Other runtime information -----------------------------------------------

* Loaded script: -e

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/enc/encdb.so
    4 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/enc/trans/transdb.so
    5 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/enc/iso_8859_1.so
    6 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/unicode_normalize.rb
    7 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/rbconfig.rb
    8 thread.rb
    9 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/thread.so
   10 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/compatibility.rb
   11 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/defaults.rb
   12 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/deprecate.rb
   13 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/errors.rb
   14 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/version.rb
   15 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/requirement.rb
   16 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/platform.rb
   17 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb
   18 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/stub_specification.rb
   19 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/util/list.rb
   20 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/stringio.so
   21 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb
   22 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/exceptions.rb
   23 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb
   24 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   25 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/monitor.rb
   26 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   27 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems.rb
   28 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/etc.so
   29 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/fileutils.rb
   30 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/rfc2396_parser.rb
   31 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/rfc3986_parser.rb
   32 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/common.rb
   33 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/generic.rb
   34 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/ftp.rb
   35 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/http.rb
   36 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/https.rb
   37 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/ldap.rb
   38 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/ldaps.rb
   39 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri/mailto.rb
   40 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/uri.rb
   41 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/date_core.so
   42 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/date.rb
   43 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/time.rb
   44 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/open-uri.rb
   45 C:/Program Files (x86)/Shoes/lib/shoes/open-uri-patch.rb
   46 C:/Program Files (x86)/Shoes/lib/shoes/HttpResponse.rb
   47 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/digest.so
   48 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/digest.rb
   49 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/openssl.so
   50 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/bn.rb
   51 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/cipher.rb
   52 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/config.rb
   53 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/digest.rb
   54 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/x509.rb
   55 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/buffering.rb
   56 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/fcntl.so
   57 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl/ssl.rb
   58 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/openssl.rb
   59 C:/Program Files (x86)/Shoes/lib/shoes/download.rb
   60 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/tmpdir.rb
   61 C:/Program Files (x86)/Shoes/lib/ruby/site_ruby/2.2.0/rubygems/path_support.rb
   62 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/exception.rb
   63 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/syntax_error.rb
   64 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/psych.so
   65 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/omap.rb
   66 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/set.rb
   67 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/class_loader.rb
   68 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/i386-mingw32/strscan.so
   69 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/scalar_scanner.rb
   70 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/node.rb
   71 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/stream.rb
   72 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/document.rb
   73 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/sequence.rb
   74 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/scalar.rb
   75 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/mapping.rb
   76 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes/alias.rb
   77 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/nodes.rb
   78 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/streaming.rb
   79 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors/visitor.rb
   80 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors/to_ruby.rb
   81 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors/emitter.rb
   82 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/handler.rb
   83 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/tree_builder.rb
   84 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors/yaml_tree.rb
   85 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/json/ruby_events.rb
   86 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors/json_tree.rb
   87 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors/depth_first.rb
   88 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/visitors.rb
   89 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/parser.rb
   90 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/coder.rb
   91 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/core_ext.rb
   92 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/deprecated.rb
   93 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/stream.rb
   94 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/json/yaml_events.rb
   95 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/json/tree_builder.rb
   96 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/json/stream.rb
   97 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych/handlers/document_stream.rb
   98 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/psych.rb
   99 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/yaml.rb
  100 C:/Program Files (x86)/Shoes/lib/shoes/vlcpath.rb
  101 C:/Program Files (x86)/Shoes/lib/shoes/cache.rb
  102 C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/optparse.rb
  103 C:/Program Files (x86)/Shoes/lib/shoes/inspect.rb
  104 C:/Program Files (x86)/Shoes/lib/shoes/image.rb
  105 C:/Program Files (x86)/Shoes/lib/shoes.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html


This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

**Comment by BackOrder** [comment]
It also segfault on the following **malformed** SVG:

```xml
<svg
   width="100"
   height="100"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
    <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
</svg>
```
```
Failed SVG: Error domain 1 code 73 on line 6 column 5 of file:///C:/gem00.svg: Couldn't find end of Start Tag svg

a.rb:4: [BUG] Segmentation fault
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0025 e:000024 CFUNC  :svg
c:0007 p:0020 s:0020 e:000019 BLOCK  a.rb:4 [FINISH]
c:0006 p:---- s:0016 e:000015 CFUNC  :each
c:0005 p:0008 s:0013 e:000012 BLOCK  a.rb:3 [FINISH]
c:0004 p:---- s:0011 e:000010 CFUNC  :instance_eval
c:0003 p:0010 s:0008 e:000007 LAMBDA eval:1 [FINISH]
c:0002 p:---- s:0004 e:000003 CFUNC  :call
c:0001 p:0000 s:0002 E:0017a4 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
-e:0:in `call'
eval:1:in `block in <main>'
eval:1:in `instance_eval'
a.rb:3:in `block in <main>'
a.rb:3:in `each'
a.rb:4:in `block (2 levels) in <main>'
a.rb:4:in `svg'

-- C level backtrace information -------------------------------------------
C:\WINDOWS\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0xc) [0x7768E5FC]
C:\WINDOWS\System32\KERNELBASE.dll(WaitForSingleObject+0x12) [0x7442AD52]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_print_backtrace+0x4b) [0x640AF005]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_vm_bugreport+0x78) [0x640AF082]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_bug_context+0x72) [0x63F7AAD6]
C:\Program Files (x86)\Shoes\msvcrt-ruby220.dll(rb_get_next_signal+0xdb) [0x640356B9]
C:\Program Files (x86)\Shoes\cshoes.exe(WinMain+0x4f6) [0x00401A56]
C:\WINDOWS\System32\KERNELBASE.dll(UnhandledExceptionFilter+0x172) [0x744BD412]
C:\WINDOWS\SYSTEM32\ntdll.dll(LdrSetAppCompatDllRedirectionCallback+0x1ae9d) [0x776BE0BD]
```
