### ISSUE TITLE
Shoes Manual parser has issues with Dash

### ISSUE THREAD

**Issue by dredknight** [Shoes3/shoes3#339]
@BackOrder , @ccoupe  I think I bumped into something.
Any of the three examples below is executed by Shoes.

```Ruby
Shoes.app( width: 400, height: 100 ) do
  line 10,40,350,40, stroke: green, strokewidth: 3
  line 10,20,350,20, stroke: green, strokewidth: 3
end
```
```Ruby
Shoes.app( width: 400, height: 100 ) do
  line 10,40,350,40, dash: :onedot, stroke: green, strokewidth: 3
  line 10,20,350,20, dash: nodot, stroke: green, strokewidth: 3
end
```
```Ruby
Shoes.app( width: 400, height: 100 ) do
  line 10,40,350,40, dash: :onedot, stroke: green, strokewidth: 3
  line 10,20,350,20, stroke: green, strokewidth: 3
end
```
Try to put the last one as a code in the manual.

{{{
Shoes.app( width: 400, height: 100 ) do
  line 10,40,350,40, dash: :onedot, stroke: green, strokewidth: 3
  line 10,20,350,20, stroke: green, strokewidth: 3
end
}}}

Launch the manual and you will get this error. The other two examples work fine.
```Ruby
Error in <unknown> line 0 | 2017-03-11 21:35:35 +0200
no implicit conversion from nil to integer
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/suffix_array_writer.rb:79:in `[]'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/suffix_array_writer.rb:79:in `block in dump_inline_suffixes'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/suffix_array_writer.rb:78:in `step'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/suffix_array_writer.rb:78:in `dump_inline_suffixes'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/suffix_array_writer.rb:69:in `dump_suffixes'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/suffix_array_writer.rb:57:in `finish!'
C:/Program Files (x86)/Shoes/lib/ruby/2.2.0/ftsearch/fragment_writer.rb:105:in `finish!'
C:/Program Files (x86)/Shoes/lib/shoes/search.rb:20:in `finish!'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:257:in `load_docs'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:453:in `block in make_help_page'
eval:1:in `instance_eval'
eval:1:in `block in <main>'
-e:1:in `call'
```

**Comment by BackOrder** [comment]
Which version of Shoes are you using? The current beta **3.3.3** no longer relies on `ftsearch`. The sample you mentioned is working here.

http://walkabout.mvmanila.com/public/shoes/

**Comment by dredknight** [comment]
Thanks. I was using the current prod 3.3.2.
With 3.3.3 it works fine but when I do a search for some reason it duplicates the results.
Try for example to search for "align".
You will see 5-6 results where the first and the last are the same.

**Comment by BackOrder** [comment]
Shoes now use [Picky](https://github.com/floere/picky) as a search engine. The current behaviour is trying to mimic Shoes former `ftsearch` as close as possible. It may need some fine tuning. However, I am not getting the extra results you are talking about.

![image](https://cloud.githubusercontent.com/assets/8844578/23827149/cda416ae-067a-11e7-8e54-b8352050a6c7.png)

**Comment by ccoupe** [comment]
I get 5 for align but I'm not running on the latest manual.  Not major issue for me but it needs to stay open until it's fixed or agreed to be a non-issue.

**Comment by BackOrder** [comment]
@dredknight thanks for changing the title. Would you mind look at all the result one-by-one? I suspect there are the word `align` multiple times in the same section, thus repeating. It would be kinda OK but could be improved.

**Comment by dredknight** [comment]
@BackOrder nice idea! I opened "align" page and the word is actually referred numerous times (4 or 5).
I tried the same with dash - it has the word in the header and twice in the text.
Unfortunately after removing the word from text nothing changed. Still the answers are double.

Could you test something on your side (v3.3.3) in the search type "dash". In the default manual vesion dash is still not present so no results should pop. However the search result says different:
![image](https://cloud.githubusercontent.com/assets/12410314/23835652/dc1097f4-0773-11e7-96c0-6f21fcf6a4f2.png)

As you may see there is no "dash" word in the result in any of the text.

![image](https://cloud.githubusercontent.com/assets/12410314/23835660/fd299cf6-0773-11e7-88d1-277a3cc5d3e1.png)

**Comment by dredknight** [comment]
I will try to dig something on my own tomorrow :D.

**Comment by BackOrder** [comment]
Open **Windows Explorer**, copy `%LOCALAPPDATA%\Shoes` and remove `index` directory. Reload Shoes Manual and Picky will reindex. Should be fine.

**Comment by dredknight** [comment]
Thanks!! I found the issue for duplication!

Article gets duplicated when the searched word can be found both in header and body at least once.

**Comment by dredknight** [comment]
I did the following test:
1. Dash - multiple times only in body - Search gives 1 result.
2. Dash - once in header once (or more) in body = 2 search results.
3. Dash - 2 or more times in header only = 2 search results.
