### ISSUE TITLE
Shape code sample in Shoes Manual is not working

### ISSUE THREAD

**Issue by BackOrder** [Shoes3/shoes3#43]
The Shoes Manual code sample for **shape(left, top) { ... }** in ***Slots > Art*** section is not working. Shoes Console is reporting that the constant PI is not initialized.

```
Error in <unknown> line 0 | 2015-01-25 13:20:02 -0500
uninitialized constant PI
<main>:4:in `block (2 levels) in <main>'
<main>:2:in `call'
<main>:2:in `shape'
<main>:2:in `block in <main>'
eval:1:in `instance_eval'
eval:1:in `block in <main>'
<main>:in `call'
<main>:in `app'
<main>:in `<main>'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:215:in `eval'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:215:in `run_code'
C:/Program Files (x86)/Shoes/lib/shoes/help.rb:64:in `block (4 levels) in dewikify_code'
-e:1:in `call'
```

**Comment by BackOrder** [comment]
The following code seems to fix the issue but no sample of the shape were provided before hand in order to ascertain its validity. The rendering is depicted below.

![image](https://cloud.githubusercontent.com/assets/8844578/5892692/479c0c8a-a496-11e4-8b4b-4f8d7af6be75.png)
```ruby
 Shoes.app do
   fill red(0.2)
   shape do
     move_to(90, 55)
     arc_to(50, 55, 50, 50, 0, Math::PI / 2)
     arc_to(50, 55, 60, 60, Math::PI / 2, Math::PI)
     arc_to(50, 55, 70, 70, Math::PI, 2 * Math::PI - Math::PI / 2)
     arc_to(50, 55, 80, 80, Math::PI, 2 * Math::PI)
   end
 end
```

**Comment by BackOrder** [comment]
PI definitions can be found in https://github.com/Shoes3/shoes3/blob/master/shoes/ruby.c. They are unfortunately unavailable at runtime. Take note that **Shoes::PI** does work.

```ruby
  rb_const_set(cTypes, rb_intern("RAD2PI"), rb_float_new(SHOES_RAD2PI));
  rb_const_set(cTypes, rb_intern("TWO_PI"), rb_float_new(SHOES_PIM2));
  rb_const_set(cTypes, rb_intern("HALF_PI"), rb_float_new(SHOES_HALFPI));
  rb_const_set(cTypes, rb_intern("PI"), rb_float_new(SHOES_PI));
```

**Comment by BackOrder** [comment]
The manual needs to be updated with the code below. The proper rendering looks like this:

![image](https://cloud.githubusercontent.com/assets/8844578/5906181/a3baa3d2-a563-11e4-91be-93c150dc99da.png)

```ruby
 Shoes.app do
   fill red(0.2)
   shape do
     move_to(90, 55)
     arc_to(50, 55, 50, 50, 0, Shoes::PI/2)
     arc_to(50, 55, 60, 60, Shoes::PI/2, Shoes::PI)
     arc_to(50, 55, 70, 70, Shoes::PI, Shoes::TWO_PI-Shoes::PI/2)
     arc_to(50, 55, 80, 80, Shoes::TWO_PI-Shoes::PI/2, Shoes::TWO_PI)
   end
 end
```
